Edit github actions to run the restructure operation

diff --git a/.github/workflows/quick-check.yml b/.github/workflows/quick-check.yml
--- a/.github/workflows/quick-check.yml
+++ b/.github/workflows/quick-check.yml
@@ -9,7 +9,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        java-version: ['11', '17', '21', '22']
+        java-version: ['11', '17', '21', '25']
     steps:
       - name: Checkout GWT itself into one directory
         uses: actions/checkout@v6
@@ -33,35 +33,33 @@ jobs:
         with:
           reviewdog_version: latest
 
-      - name: Build, style/api checks, produce docs
-        # Presently this runs no tests at all, but could run quick tests
-        run: |
-          set -eux
-          cd gwt
-          # Set env vars to ensure we get the build we expect
-          export \
-            TZ=America/Los_Angeles \
-            ANT_OPTS=-Dfile.encoding=UTF8 \
-            ANT_OPTS=-Xmx2g
-          ant clean compile.tests dist doc checkstyle apicheck
-
-      - name: Create pull request comments/annotations for checkstyle from the java 21 build, even on failure
-        if: ${{ always() && github.event_name == 'pull_request' && matrix.java-version == '21' }}
-        env:
-          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          REVIEWDOG_SKIP_DOGHOUSE: true
-        run: |
-          set -eux
-          shopt -s globstar
-          cd gwt
-          for f in build/out/**/checkstyle*.xml ; do
-            echo $f
-            reviewdog -f=checkstyle -filter-mode=diff_context -reporter=github-pr-annotations -level=info < $f
-          done
-      - name: Upload checkstyle xml for manual review
-        uses: actions/upload-artifact@v6
-        if: ${{ matrix.java-version == '21' }}
+      - name: Restructure the project to use maven
+        run: ./restructure.sh
+      - name: Build the project with Maven
+        run: mvn -f ideal/pom.xml clean install --batch-mode
+      - name: Report test results
+        uses: mikepenz/action-junit-report@v6.0.0
+        if: always()
         with:
-          name: checkstyle-reports-java${{ matrix.java-version }}
-          path: 'gwt/build/out/**/checkstyle*.xml'
-          retention-days: 5
+          report_paths: '**/target/surefire-reports/TEST-*.xml'
+
+#      - name: Create pull request comments/annotations for checkstyle from the java 21 build, even on failure
+#        if: ${{ always() && github.event_name == 'pull_request' && matrix.java-version == '21' }}
+#        env:
+#          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#          REVIEWDOG_SKIP_DOGHOUSE: true
+#        run: |
+#          set -eux
+#          shopt -s globstar
+#          cd gwt
+#          for f in build/out/**/checkstyle*.xml ; do
+#            echo $f
+#            reviewdog -f=checkstyle -filter-mode=diff_context -reporter=github-pr-annotations -level=info < $f
+#          done
+#      - name: Upload checkstyle xml for manual review
+#        uses: actions/upload-artifact@v6
+#        if: ${{ matrix.java-version == '21' }}
+#        with:
+#          name: checkstyle-reports-java${{ matrix.java-version }}
+#          path: 'gwt/build/out/**/checkstyle*.xml'
+#          retention-days: 5
