Edit github actions to run the restructure operation

diff --git a/.github/workflows/quick-check.yml b/.github/workflows/quick-check.yml
--- a/.github/workflows/quick-check.yml
+++ b/.github/workflows/quick-check.yml
@@ -34,36 +34,31 @@ jobs:
         with:
           reviewdog_version: latest
 
-      - name: Build, style/api checks, produce docs
-        # Presently this runs no tests at all, but could run quick tests
-        run: |
-          set -eux
-          cd gwt
-          # Set env vars to ensure we get the build we expect
-          export \
-            TZ=America/Los_Angeles \
-            ANT_OPTS=-Dfile.encoding=UTF8 \
-            ANT_OPTS=-Xmx2g
-          ant clean compile.tests dist doc checkstyle apicheck | tee log.txt
-
-      - name: Create pull request comments/annotations for Checkstyle and ErrorProne from the java 21 build, even on failure
-        if: ${{ always() && github.event_name == 'pull_request' && matrix.java-version == '21' }}
-        env:
-          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          REVIEWDOG_SKIP_DOGHOUSE: true
-        run: |
-          set -eux
-          shopt -s globstar
-          cd gwt
-          for f in build/out/**/checkstyle*.xml ; do
-            echo $f
-            reviewdog -f=checkstyle -filter-mode=diff_context -reporter=github-pr-annotations -level=info < $f || true
-          done
-          reviewdog -efm="    [javac] %f:%l: warning: %m" -filter-mode=diff_context -reporter=github-pr-annotations -level=info < log.txt || true
-      - name: Upload checkstyle xml for manual review
-        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
-        if: ${{ matrix.java-version == '21' }}
-        with:
-          name: checkstyle-reports-java${{ matrix.java-version }}
-          path: 'gwt/build/out/**/checkstyle*.xml'
-          retention-days: 5
+      - name: Restructure the project to use maven
+        run: ./restructure.sh
+      - name: Build the project with Maven
+        run: mvn -f ideal/pom.xml clean install --batch-mode -DskipTests
+#      - name: Report test results
+#        uses: mikepenz/action-junit-report@v6.0.0
+#        if: always()
+#      - name: Create pull request comments/annotations for Checkstyle and ErrorProne from the java 21 build, even on failure
+#        if: ${{ always() && github.event_name == 'pull_request' && matrix.java-version == '21' }}
+#        env:
+#          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#          REVIEWDOG_SKIP_DOGHOUSE: true
+#        run: |
+#          set -eux
+#          shopt -s globstar
+#          cd gwt
+#          for f in build/out/**/checkstyle*.xml ; do
+#            echo $f
+#            reviewdog -f=checkstyle -filter-mode=diff_context -reporter=github-pr-annotations -level=info < $f || true
+#          done
+#          reviewdog -efm="    [javac] %f:%l: warning: %m" -filter-mode=diff_context -reporter=github-pr-annotations -level=info < log.txt || true
+#      - name: Upload checkstyle xml for manual review
+#        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
+#        if: ${{ matrix.java-version == '21' }}
+#        with:
+#          name: checkstyle-reports-java${{ matrix.java-version }}
+#          path: 'gwt/build/out/**/checkstyle*.xml'
+#          retention-days: 5
